/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects_.$projectId_.settings'
import { Route as OrganizationsOrganizationIdTeamsRouteImport } from './routes/organizations.$organizationId.teams'
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations.$organizationId.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects_/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdTeamsRoute =
  OrganizationsOrganizationIdTeamsRouteImport.update({
    id: '/organizations/$organizationId/teams',
    path: '/organizations/$organizationId/teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/organizations/$organizationId/settings',
    path: '/organizations/$organizationId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId/teams': typeof OrganizationsOrganizationIdTeamsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId/teams': typeof OrganizationsOrganizationIdTeamsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId/teams': typeof OrganizationsOrganizationIdTeamsRoute
  '/projects_/$projectId_/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/teams'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/teams'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/teams'
    | '/projects_/$projectId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRoute
  OrganizationsOrganizationIdTeamsRoute: typeof OrganizationsOrganizationIdTeamsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/settings': {
      id: '/projects_/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/teams': {
      id: '/organizations/$organizationId/teams'
      path: '/organizations/$organizationId/teams'
      fullPath: '/organizations/$organizationId/teams'
      preLoaderRoute: typeof OrganizationsOrganizationIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings'
      path: '/organizations/$organizationId/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  OrganizationsOrganizationIdSettingsRoute:
    OrganizationsOrganizationIdSettingsRoute,
  OrganizationsOrganizationIdTeamsRoute: OrganizationsOrganizationIdTeamsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
